url: "https://mbaglo.github.io"
plugins:
  - jekyll-sitemap
title: "Chinyere Gloria Mbaka"
email: "60557047+mbaglo@users.noreply.github.com"
description: ""
baseurl: ""
permalink: pretty
theme: minima
author: "Chinyere Gloria Mbaka"
